#!/bin/bash

# Switch to the db2inst1 user and define functions
su - db2inst1 << 'EOF' | grep -v 'Last'
# DB2 connection details
DB_USER="db2inst1"
DB_PASS="abcd1234"
DB_NAME="pegadb"

# Function to execute DB2 queries
execute_db2_query() {
    db2 connect to $DB_NAME > /dev/null 2>&1
    db2 -x "$1"
}

# Function to get Bufferpools, TOTALHIT, and IDXHIT
get_bufferpool_stats() {
    execute_db2_query "SELECT BP_NAME as bufferpool, TOTAL_HIT_RATIO_PERCENT AS totalhit, INDEX_HIT_RATIO_PERCENT AS idxhit FROM SYSIBMADM.BP_HITRATIO where bp_name not like 'IBMSYSTEM%'"
}

# Call function to collect buffer pool stats
bufferpool_stats=$(get_bufferpool_stats)

# Output data in JSON format
echo '['
first=true
echo "$bufferpool_stats" | while read -r line; do
    if [ "$first" = true ]; then
        first=false
    else
        echo ","
    fi
    # Extracting bufferpool, totalhit, and idxhit using awk
    echo "$line" | awk '{printf "{\"{#BUFFERPOOL}\":\"%s\",\"TotalHit\":\"%s\",\"IdxHit\":\"%s\"}", $1, $2, $3}'
done
echo ']'

EOF

