#!/bin/bash

# DB2 connection details
DB_USER="your_db_username"
DB_PASS="your_db_password"
DB_NAME="pegadb"

# Function to execute DB2 queries
execute_db2_query() {
  echo "$DB_PASS" | su - $DB_USER -c "db2 connect to $DB_NAME > /dev/null 2>&1 && db2 -x \"$1\""
}

# Function to check DB2 connection status
check_db2_connection() {
  execute_db2_query "exit" > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "DB2 connection successful."
    return 0
  else
    echo "DB2 connection failed."
    return 1
  fi
}

# Main script starts here

# Check DB2 connection
check_db2_connection || exit 1

# SQL Query
QUERY="SELECT BP_NAME as bufferpool, TOTAL_HIT_RATIO_PERCENT AS totalhit, INDEX_HIT_RATIO_PERCENT AS idxhit FROM SYSIBMADM.BP_HITRATIO WHERE BP_NAME NOT LIKE 'IBMSYSTEM%'"

# Execute the query and fetch the data
result=$(execute_db2_query "$QUERY")

# Process the result
IFS=$'\n'

echo "Sending data to Zabbix..."
for line in $result; do
  bufferpool=$(echo $line | awk '{print $1}')
  totalhit=$(echo $line | awk '{print $2}')
  idxhit=$(echo $line | awk '{print $3}')
  
  echo "Bufferpool: $bufferpool, Total Hit Ratio: $totalhit, Index Hit Ratio: $idxhit"

  # Send the data to Zabbix
  # Replace ZABBIX_SERVER and ZABBIX_HOST with your Zabbix server address and host name
  zabbix_sender -z <Zabbix server address> -s <Host name> -k bufferpool.totalhit[$bufferpool] -o $totalhit
  echo "Sent: bufferpool.totalhit[$bufferpool] with value $totalhit"

  zabbix_sender -z <Zabbix server address> -s <Host name> -k bufferpool.idxhit[$bufferpool] -o $idxhit
  echo "Sent: bufferpool.idxhit[$bufferpool] with value $idxhit"

done

echo "All data sent successfully."
