#!/bin/sh

# Define the path to the JSON file
JSON_FILE="/etc/zabbix/scripts/tablespace_data.json"

# Switch to the db2inst1 user and define functions
su - db2inst1 << 'EOF' > $JSON_FILE
# DB2 connection details
DB_USER="db2inst1"
DB_PASS="abcd1234"
DB_NAME="pegadb"

# Function to execute DB2 queries
execute_db2_query() {
    db2 connect to $DB_NAME > /dev/null 2>&1
    db2 -x "$1"
}

# Function to get Tablespace, USEDKB, and TOTALKB
get_tablespace_stats() {
    execute_db2_query "SELECT tbsp_name as TABLESPACE, sum(tbsp_used_size_kb)/1024 as usedkb, sum(tbsp_total_size_kb)/1024 as totalkb FROM SYSIBMADM.TBSP_UTILIZATION GROUP BY tbsp_name"
}

# Call function to collect tablespace stats
tablespace_stats=$(get_tablespace_stats)

# Write data in JSON format to the JSON file
echo '['
first=true
echo "$tablespace_stats" | while read -r line; do
    if [ "$first" = true ]; then
        first=false
    else
        echo ","
    fi
    # Extracting tablespace, usedkb, and totalkb using awk
    echo "$line" | awk '{print "{\"{#TABLESPACE}\":\"" $1 "\",\"UsedKB\":\"" $2 "\",\"TotalKB\":\"" $3 "\"}"}'
done
echo ']'

EOF

# Remove the 'Last' keyword from the output
sed -i '/Last/d' $JSON_FILE
